### ISSUE TITLE
Provide way for user stylesheet to override specificity rules

### ISSUE THREAD

**Issue by michael-n-cooper** [w3c/css-a11y#3] opened 2017-04-20 15:59 UTC
This issue was originally raised in the APA tracker as [ISSUE-625](https://www.w3.org/WAI/APA/track/issues/625). Migrating to CSS A11Y.

**Comment by patrickhlauke** [comment] 2017-04-23 20:02
copying the context from @jnurthen over here:

> CSS Cascading and Inheritance http://www.w3.org/TR/css3-cascade/#cascading needs to provide a method to override the specificity rules to allow a user specified style to override author specified styles.
>
> Take for example the following scenario. The user requires all text to have increased line spacing so they want to set 
> `* {line-height: 2;!important}` in their user CSS.
>
> This works fine until the author has specified something like
>
> `UL LI {line-height: 1.1;}` in the author CSS which, due to the higher specificity will override the user stylesheet despite the !important.

**Comment by patrickhlauke** [comment] 2017-04-23 20:09
and now in response to that: unless I'm misreading https://www.w3.org/TR/css3-cascade/#cascade-origin  it is already specified that important user styles take precedence over author-defined styles.

i'd note that @jnurthen's example CSS has the `!important` in the wrong place...in needs to come before the `;`

with that alteration, i've just tested this using just `* { line-height: 2 !important; }` in a user stylesheet, setting IE11 to load this (via Internet Options > Accessibility > User Style Sheet). loading a test page that explicitly sets something very specific like `ul#foo li { line-height: 1.1 !important; }` (note the id selector and `!important`, making this quite specific and, well, important) still results in the user style trumping this author setting.

note that not many modern browsers offer true user stylesheet support. while there are extensions that serve a nominally same purpose, these usually just inject styles into the document, meaning that whatever "user styles" are set are not in fact real user styles as far as the browser is concerned, but are on par with author styles (and therefore exhibit the usual specificity problems)

**Comment by thierryk** [comment] 2017-04-23 20:22
I think it makes sense since we could not expect users to know which "hooks" they should use to *trump* the specificity of styles from author styles sheets.

**Comment by patrickhlauke** [comment] 2017-04-23 20:29
@thierryk my point is that this is exactly what's currently possible. a simple "*" selector, when used in the user stylesheet, currently already trumps a very specific `ul#foo li { ... !important }`. so the whole issue here is moot, i think, as it asks for something that's already implemented?

**Comment by AmeliaBR** [comment] 2017-04-23 20:46
> the whole issue here is moot, i think, as it asks for something that's already implemented?

Yes, this is exactly the use case behind the CSS cascade order and `!important`.

In practice, this is complicated by the fact that most browsers don't have a proper interface anymore to *set* user styles.  Browser extensions for adding user styles do so by injecting `<style>` or `<link>` elements into the DOM, which means that they get treated as author styles, not user styles, in the cascade.  `!important` will still override regular declarations, whatever the specificity, but if the website uses `!important` as well, then the injected styles don't have the cascade priority that real user styles would have. But this is less of a spec issue, and more of a browser support issue.

**Comment by thierryk** [comment] 2017-04-23 20:46
@patrickhlauke I know, this is why I 👍  your comment and confirmed that what you reported is the only way things could work.

**Comment by patrickhlauke** [comment] 2017-04-23 20:49
@thierryk ah sorry, i misunderstood you there :)

**Comment by thierryk** [comment] 2017-04-23 21:07
> but if the website uses !important as well, then the injected styles don't have the cascade priority that real user styles would have.

As a side note, users of these add-ons can always make things work as it is possible to *increase specificity* without relying on existing hooks, for example:

```css
:not(#\#):not(#\#):not(#\#) {
  line-height: 2 !important;
}
```

**Comment by 7mary4** [comment] 2017-04-24 20:41
To summarize:
@patrickhlauke noticed the original code had the !important after the semi-colon. Testing with the !important in the correct position provides the expected specificity for user stylesheets. 
@thierryk  also gave an example of using selectors to make the user style more specific than author-defined styles. 
It looks like we could close this issue, as the user styles still provide the correct cascading specificity.

Are there any objections to closing this? If so, what should be the focus of extended evaluations?

**Comment by thierryk** [comment] 2017-04-24 20:51
> @thierryk also gave an example of using selectors to make the user style more specific than author-defined styles.

Actually, my workaround is meant to trump authors styles when using add-ons (i.e. [stylish](https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe)). There should be no need to increase (selector) specificity in users styles sheets to overwrite author-defined styles.

Yes, I think we can close this.

**Comment by digilou** [comment] 2020-07-29 16:33
Reviewed this ticket with APA. They will consult low vision users and need for this with CSS WG.

**Comment by digilou** [comment] 2020-08-05 16:48
Use cases for user personalization were gathered by @becka11y from Wayne Dick. These use cases will be added to a W3C wiki to continue discussion about personalization items being added to [Media Query Module 5](https://drafts.csswg.org/mediaqueries-5/).

**Closed by digilou** 2020-08-05 16:48 UTC
Labels: enhancement
